package com.wechantloup.thermostat.ui.theme

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

class Dimensions(
    val spacing1v: Dp,
    val spacing1w: Dp,
    val spacing3v: Dp,
    val spacing2w: Dp,
    val spacing3w: Dp,
    val spacing4w: Dp,
    val spacing5w: Dp,
    val spacing6w: Dp,
    val spacing8w: Dp,
    val roundedCornerSizeM: Dp,
    val roundedCornerSizeS: Dp,
    val totallyRoundedCorner: Dp,
    val elevationNone: Dp,
    val elevationXxs: Dp,
    val elevationXs: Dp,
    val elevationS: Dp,
    val elevationM: Dp,
    val elevationL: Dp,
    val elevationXl: Dp,
    val btnSizeM: Dp,
    val btnSizeS: Dp,
    val btnSizeXs: Dp,
    val btnIconSizeS: Dp,
    val btnIconSizeM: Dp,
    val btnHorizontalPaddingM: Dp,
    val btnVerticalPaddingM: Dp,
    val btnHorizontalPaddingS: Dp,
    val btnHorizontalPaddingXs: Dp,
    val dialogTitleImageHeight: Dp,
)

val defaultDimensions = Dimensions(
    spacing1v = 4.dp,
    spacing1w = 8.dp,
    spacing3v = 12.dp,
    spacing2w = 16.dp,
    spacing3w = 24.dp,
    spacing4w = 32.dp,
    spacing5w = 40.dp,
    spacing6w = 48.dp,
    spacing8w = 64.dp,
    roundedCornerSizeM = 18.dp,
    roundedCornerSizeS = 14.dp,
    totallyRoundedCorner = 32.dp,
    elevationNone = 0.dp,
    elevationXxs = 2.dp,
    elevationXs = 4.dp,
    elevationS = 6.dp,
    elevationM = 8.dp,
    elevationL = 12.dp,
    elevationXl = 16.dp,
    btnSizeM = 48.dp,
    btnSizeS = 40.dp,
    btnSizeXs = 32.dp,
    btnIconSizeS = 16.dp,
    btnIconSizeM = 24.dp,
    btnHorizontalPaddingM = 32.dp,
    btnVerticalPaddingM = 16.dp,
    btnHorizontalPaddingS = 24.dp,
    btnHorizontalPaddingXs = 12.dp,
    dialogTitleImageHeight = 180.dp,
)
